// This file is generated by CreateTable.java...

public class Course {

	public int cid;
	public String title;
	public String semester;

	public Course () { 
		cid = 0;
		title = null;
		semester = null;
	}

	public Course(int cid, String title, String semester) {
		this.cid = cid;
		this.title = title;
		this.semester = semester;
	}

	public int getcid () {
		return cid;
	}
	public String gettitle () {
		return title;
	}
	public String getsemester () {
		return semester;
	}

	public void setcid (int cid) {
		this.cid = cid;
	}
	public void settitle (String title) {
		this.title = title;
	}
	public void setsemester (String semester) {
		this.semester = semester;
	}

}
