/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 6;
  /** RegularExpression Id. */
  int TABLE = 7;
  /** RegularExpression Id. */
  int USE = 8;
  /** RegularExpression Id. */
  int DATABASE = 9;
  /** RegularExpression Id. */
  int DATABASES = 10;
  /** RegularExpression Id. */
  int INSERT = 11;
  /** RegularExpression Id. */
  int INTO = 12;
  /** RegularExpression Id. */
  int VALUES = 13;
  /** RegularExpression Id. */
  int UPDATE = 14;
  /** RegularExpression Id. */
  int SET = 15;
  /** RegularExpression Id. */
  int SHOW = 16;
  /** RegularExpression Id. */
  int PARENTHESES = 17;
  /** RegularExpression Id. */
  int TYPE = 18;
  /** RegularExpression Id. */
  int STAR = 19;
  /** RegularExpression Id. */
  int SELECT = 20;
  /** RegularExpression Id. */
  int FROM = 21;
  /** RegularExpression Id. */
  int WHERE = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int EXIT = 24;
  /** RegularExpression Id. */
  int EQUAL = 25;
  /** RegularExpression Id. */
  int GREATERTHAN = 26;
  /** RegularExpression Id. */
  int LESSTHAN = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int DIGITS = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int CHAR = 31;
  /** RegularExpression Id. */
  int QUOTE = 32;
  /** RegularExpression Id. */
  int STRING = 33;
  /** RegularExpression Id. */
  int DASH = 34;
  /** RegularExpression Id. */
  int SEMICOLON = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\",\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<CREATE>",
    "<TABLE>",
    "<USE>",
    "<DATABASE>",
    "<DATABASES>",
    "<INSERT>",
    "<INTO>",
    "<VALUES>",
    "<UPDATE>",
    "<SET>",
    "<SHOW>",
    "<PARENTHESES>",
    "<TYPE>",
    "\"*\"",
    "<SELECT>",
    "<FROM>",
    "<WHERE>",
    "<AND>",
    "<EXIT>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "<DIGIT>",
    "<DIGITS>",
    "<DOUBLE>",
    "<CHAR>",
    "\"\\\"\"",
    "<STRING>",
    "\"-\"",
    "\";\"",
  };

}
