// This file is generated by CreateTable.java...

public class Professor {

	public int pid;
	public String pname;

	public Professor () { 
		pid = 0;
		pname = null;
	}

	public Professor(int pid, String pname) {
		this.pid = pid;
		this.pname = pname;
	}

	public int getpid () {
		return pid;
	}
	public String getpname () {
		return pname;
	}

	public void setpid (int pid) {
		this.pid = pid;
	}
	public void setpname (String pname) {
		this.pname = pname;
	}

}
