// This file is generated by CreateTable.java...

public class Student {

	public int sid;
	public String sname;
	public double gpa;

	public Student () { 
		sid = 0;
		sname = null;
		gpa = 0;
	}

	public Student(int sid, String sname, double gpa) {
		this.sid = sid;
		this.sname = sname;
		this.gpa = gpa;
	}

	public int getsid () {
		return sid;
	}
	public String getsname () {
		return sname;
	}
	public double getgpa () {
		return gpa;
	}

	public void setsid (int sid) {
		this.sid = sid;
	}
	public void setsname (String sname) {
		this.sname = sname;
	}
	public void setgpa (double gpa) {
		this.gpa = gpa;
	}

}
