// This file is generated by CreateTable.java...

public class Teaches {

	public int tepid;
	public int tecid;

	public Teaches () { 
		tepid = 0;
		tecid = 0;
	}

	public Teaches(int tepid, int tecid) {
		this.tepid = tepid;
		this.tecid = tecid;
	}

	public int gettepid () {
		return tepid;
	}
	public int gettecid () {
		return tecid;
	}

	public void settepid (int tepid) {
		this.tepid = tepid;
	}
	public void settecid (int tecid) {
		this.tecid = tecid;
	}

}
